"""Initial migration

Revision ID: e505a27cda14
Revises: 
Create Date: 2023-11-01 13:50:20.863265-04:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e505a27cda14'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff')
    op.drop_table('tbl_prefix')
    op.drop_table('tbl_dorm_managers')
    op.drop_table('tbl_dorm_rooms')
    op.drop_table('tbl_suffix')
    op.drop_table('faculty')
    op.drop_table('tbl_role')
    op.drop_table('tbl_comments')
    op.drop_table('tbl_dorms')
    op.drop_table('tbl_users')
    op.alter_column('tbl_ethnicity', 'ethnicity_name',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('tbl_levels', 'level_name',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.alter_column('tbl_levels', 'level_abbrev',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.drop_column('tbl_nationality', 'nationality_nation')
    op.alter_column('tbl_state', 'state_name',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.drop_column('tbl_state', 'state_abbrev')
    op.alter_column('tbl_status', 'student_status',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.drop_index('student_level', table_name='tbl_student')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('student_level', 'tbl_student', ['student_level_id'], unique=False)
    op.alter_column('tbl_status', 'student_status',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.add_column('tbl_state', sa.Column('state_abbrev', mysql.VARCHAR(length=45), nullable=True))
    op.alter_column('tbl_state', 'state_name',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.add_column('tbl_nationality', sa.Column('nationality_nation', mysql.VARCHAR(length=45), nullable=False))
    op.alter_column('tbl_levels', 'level_abbrev',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('tbl_levels', 'level_name',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('tbl_ethnicity', 'ethnicity_name',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    op.create_table('tbl_users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('prefix_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('suffix_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('address2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('state_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('zip', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('profile_picture', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('account_status_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('registration_date', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['account_status_id'], ['tbl_status.student_status_id'], name='tbl_users_ibfk_5'),
    sa.ForeignKeyConstraint(['prefix_id'], ['tbl_prefix.prefix_id'], name='tbl_users_ibfk_1'),
    sa.ForeignKeyConstraint(['role_id'], ['tbl_role.role_id'], name='tbl_users_ibfk_3'),
    sa.ForeignKeyConstraint(['state_id'], ['tbl_state.state_id'], name='tbl_users_ibfk_4'),
    sa.ForeignKeyConstraint(['suffix_id'], ['tbl_suffix.suffix_id'], name='tbl_users_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_dorms',
    sa.Column('dorm_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('dorm_name', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('dorm_phone', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('dorm_capacity', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('dm_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dm_id'], ['tbl_dorm_managers.dm_id'], name='tbl_dorms_ibfk_1'),
    sa.PrimaryKeyConstraint('dorm_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_comments',
    sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('comment_text', mysql.VARCHAR(length=2500), nullable=True),
    sa.Column('comment_by', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('comment_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['tbl_student.student_id'], name='tbl_comments_ibfk_1'),
    sa.PrimaryKeyConstraint('comment_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_role',
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('role_name', mysql.VARCHAR(length=11), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('faculty',
    sa.Column('faculty_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('department', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('address2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('zip', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('emergency_contact_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('emergency_contact_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('emergency_contact_phone', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('faculty_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_suffix',
    sa.Column('suffix_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('suffix', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('suffix_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_dorm_rooms',
    sa.Column('droom_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('droom_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('droom_capacity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('droom_notes', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('droom_phone', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('droom_floor', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('droom_unit', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('dorm_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dorm_id'], ['tbl_dorms.dorm_id'], name='tbl_dorm_rooms_ibfk_1'),
    sa.PrimaryKeyConstraint('droom_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_dorm_managers',
    sa.Column('dm_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('dm_name', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('dm_phone', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('dm_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_prefix',
    sa.Column('prefix_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('prefix_name', mysql.VARCHAR(length=11), nullable=False),
    sa.PrimaryKeyConstraint('prefix_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('staff',
    sa.Column('staff_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('emergency_contact', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('staff_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
