"""empty message

Revision ID: 0f34b0c8b9a5
Revises: e1d8cbbb9fdd
Create Date: 2023-11-09 12:18:26.884248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f34b0c8b9a5'
down_revision = 'e1d8cbbb9fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_dorm_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tbl_student', ['student_id'], ['student_id'])

    with op.batch_alter_table('tbl_nationality', schema=None) as batch_op:
        batch_op.drop_column('nationality_nation')

    with op.batch_alter_table('tbl_student', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tbl_levels', ['student_level_id'], ['level_id'])

    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tbl_account_statuses', ['acc_status_id'], ['acc_status_id'])
    
    with op.batch_alter_table('tbl_housing', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_housing_dorm_rooms', 'tbl_dorm_rooms', ['dorm_rooms_id'], ['droom_id'])
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('tbl_student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('tbl_nationality', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality_nation', mysql.VARCHAR(length=45), nullable=False))

    with op.batch_alter_table('tbl_dorm_rooms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
