"""added dormitory and room tables

Revision ID: 2de6de1d8403
Revises: 805e5b40e1f1
Create Date: 2023-11-21 12:13:23.110992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2de6de1d8403'
down_revision = '805e5b40e1f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_dormitory',
    sa.Column('dormitory_id', sa.Integer(), nullable=False),
    sa.Column('dormitory_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('dormitory_id')
    )
    op.create_table('tbl_dorm_manager',
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('manager_name', sa.String(length=100), nullable=False),
    sa.Column('dormitory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dormitory_id'], ['tbl_dormitory.dormitory_id'], ),
    sa.PrimaryKeyConstraint('manager_id')
    )
    op.create_table('tbl_room',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('dormitory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dormitory_id'], ['tbl_dormitory.dormitory_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('tbl_student_room_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['tbl_room.room_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['tbl_student.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tbl_student', schema=None) as batch_op:
        batch_op.drop_column('dorm_room_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dorm_room_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    op.drop_table('tbl_student_room_assignment')
    op.drop_table('tbl_room')
    op.drop_table('tbl_dorm_manager')
    op.drop_table('tbl_dormitory')
    # ### end Alembic commands ###
