"""new student and dorm room models

Revision ID: 426a10f0823e
Revises: 8cb9c80333a7
Create Date: 2023-11-29 13:05:24.789210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '426a10f0823e'
down_revision = '8cb9c80333a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_room')
    with op.batch_alter_table('dorm_room', schema=None) as batch_op:
        batch_op.drop_constraint('dorm_room_ibfk_2', type_='foreignkey')
        batch_op.drop_column('student_id')

    with op.batch_alter_table('tbl_student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dorm_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'dorm_room', ['room_id'], ['id'])
        batch_op.create_foreign_key(None, 'dorm', ['dorm_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('room_id')
        batch_op.drop_column('dorm_id')

    with op.batch_alter_table('dorm_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('dorm_room_ibfk_2', 'tbl_student', ['student_id'], ['student_id'])

    op.create_table('student_room',
    sa.Column('student_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('room_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['dorm_room.id'], name='student_room_ibfk_1'),
    sa.ForeignKeyConstraint(['student_id'], ['tbl_student.student_id'], name='student_room_ibfk_2'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
