"""adding dorm rooms 

Revision ID: 6ad3c412a9de
Revises: d7d57f4f5d5f
Create Date: 2023-11-24 12:19:09.539453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad3c412a9de'
down_revision = 'd7d57f4f5d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dorm_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=10), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('dorm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dorm_id'], ['dorm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dorm_room')
    # ### end Alembic commands ###
