"""add fields for assigning dorms

Revision ID: 712c2dfc4ea7
Revises: 7e2789368e9b
Create Date: 2023-11-25 17:37:00.012958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712c2dfc4ea7'
down_revision = '7e2789368e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dorm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))

    with op.batch_alter_table('dorm_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_capacity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dorm_room', schema=None) as batch_op:
        batch_op.drop_column('current_capacity')

    with op.batch_alter_table('dorm', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
