"""removed housing tables

Revision ID: 805e5b40e1f1
Revises: c86b293f23a8
Create Date: 2023-11-20 20:02:16.714936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '805e5b40e1f1'
down_revision = 'c86b293f23a8'
branch_labels = None
depends_on = None


def upgrade():
    
    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
