"""initial Migration

Revision ID: 83342d2ba5f5
Revises: 
Create Date: 2023-11-22 11:34:39.420335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83342d2ba5f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_room', schema=None) as batch_op:
        batch_op.drop_constraint('fk_room_student_assignment', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_room', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_room_student_assignment', 'tbl_student_room_assignment', ['room_id'], ['room_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
