"""first Migration

Revision ID: 8c16305df9cb
Revises: 
Create Date: 2023-11-12 11:17:12.433545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c16305df9cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_student', schema=None) as batch_op:
        batch_op.create_index('ix_tbl_student_dorm_room_id_unique', ['dorm_room_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_student', schema=None) as batch_op:
        batch_op.drop_index(None, table_name='tbl_student')

    # ### end Alembic commands ###
