"""create association table for students and dorm rooms

Revision ID: 93da4b6b2d18
Revises: 712c2dfc4ea7
Create Date: 2023-11-28 15:42:55.941030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93da4b6b2d18'
down_revision = '712c2dfc4ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_room',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['dorm_room.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['tbl_student.student_id'], )
    )
    with op.batch_alter_table('tbl_student', schema=None) as batch_op:
        batch_op.drop_constraint('tbl_student_ibfk_12', type_='foreignkey')
        batch_op.drop_column('dorm_room_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dorm_room_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('tbl_student_ibfk_12', 'dorm_room', ['dorm_room_id'], ['id'])

    op.drop_table('student_room')
    # ### end Alembic commands ###
