"""resolving discrepencies

Revision ID: a1cee89b5812
Revises: 83342d2ba5f5
Create Date: 2023-11-22 11:52:32.856080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1cee89b5812'
down_revision = '83342d2ba5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('tbl_student_room_assignment')
    # op.drop_table('tbl_room')
    op.drop_table('tbl_dormitory')
    op.drop_table('tbl_dorm_manager')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_dorm_manager',
    sa.Column('manager_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('manager_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('dormitory_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dormitory_id'], ['tbl_dormitory.dormitory_id'], name='tbl_dorm_manager_ibfk_1'),
    sa.PrimaryKeyConstraint('manager_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_dormitory',
    sa.Column('dormitory_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('dormitory_name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('dormitory_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_room',
    sa.Column('room_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('room_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('dormitory_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dormitory_id'], ['tbl_dormitory.dormitory_id'], name='tbl_room_ibfk_1'),
    sa.PrimaryKeyConstraint('room_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tbl_student_room_assignment',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('room_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['tbl_room.room_id'], name='tbl_student_room_assignment_ibfk_1'),
    sa.ForeignKeyConstraint(['student_id'], ['tbl_student.student_id'], name='tbl_student_room_assignment_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
