"""first migration

Revision ID: e1d8cbbb9fdd
Revises: 
Create Date: 2023-11-07 19:11:11.777318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1d8cbbb9fdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    if not conn.dialect.has_table(conn, 'staff'):
        op.create_table('staff',
            sa.Column('staff_id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=True),
            sa.Column('phone_number', sa.String(length=20), nullable=True),
            sa.Column('email', sa.String(length=255), nullable=True),
            sa.Column('address', sa.String(length=255), nullable=True),
            sa.Column('emergency_contact', sa.String(length=255), nullable=True),
            sa.PrimaryKeyConstraint('staff_id')
        )
    
    with op.batch_alter_table('tbl_divisions', schema=None) as batch_op:
        batch_op.alter_column('division_name',
               existing_type=mysql.VARCHAR(length=11),
               type_=sa.String(length=45),
               existing_nullable=False)

    with op.batch_alter_table('tbl_ethnicity', schema=None) as batch_op:
        batch_op.alter_column('ethnicity_name',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)

    with op.batch_alter_table('tbl_housing', schema=None) as batch_op:
       
        batch_op.alter_column('student_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('tbl_levels', schema=None) as batch_op:
        batch_op.alter_column('level_name',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
        batch_op.alter_column('level_abbrev',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)

    with op.batch_alter_table('tbl_role', schema=None) as batch_op:
        batch_op.alter_column('role_name',
               existing_type=mysql.VARCHAR(length=11),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('tbl_state', schema=None) as batch_op:
        batch_op.alter_column('state_name',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)

    with op.batch_alter_table('tbl_status', schema=None) as batch_op:
        batch_op.alter_column('student_status',
               existing_type=sa.String(length=45),
               nullable=False)

    with op.batch_alter_table('tbl_student', schema=None) as batch_op:
        batch_op.alter_column('student_enrolled',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.Date(),
               existing_nullable=True)

        batch_op.create_foreign_key(None, 'tbl_divisions', ['student_division_id'], ['division_id'])

    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.drop_index('account_status_id')
        
    with op.batch_alter_table('tbl_dorm_rooms', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_dorm_room_student', 'tbl_student', ['student_id'], ['student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.create_index('account_status_id', ['acc_status_id'], unique=False)

    with op.batch_alter_table('tbl_student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('student_level', ['student_level_id'], unique=False)
        batch_op.create_index('student_division', ['student_division_id'], unique=False)
        batch_op.alter_column('student_enrolled',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)

    with op.batch_alter_table('tbl_status', schema=None) as batch_op:
        batch_op.alter_column('student_status',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)

    with op.batch_alter_table('tbl_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_abbrev', mysql.VARCHAR(length=45), nullable=True))
        batch_op.alter_column('state_name',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)

    with op.batch_alter_table('tbl_role', schema=None) as batch_op:
        batch_op.alter_column('role_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=11),
               existing_nullable=True)

    with op.batch_alter_table('tbl_nationality', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality_nation', mysql.VARCHAR(length=45), nullable=False))

    with op.batch_alter_table('tbl_levels', schema=None) as batch_op:
        batch_op.alter_column('level_abbrev',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('level_name',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)

    with op.batch_alter_table('tbl_housing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dorm_rooms_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tbl_housing_ibfk_1', 'tbl_dorm_rooms', ['dorm_rooms_id'], ['droom_id'])
        batch_op.alter_column('student_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('droom_id')

    with op.batch_alter_table('tbl_ethnicity', schema=None) as batch_op:
        batch_op.alter_column('ethnicity_name',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)

    with op.batch_alter_table('tbl_divisions', schema=None) as batch_op:
        batch_op.alter_column('division_name',
               existing_type=sa.String(length=45),
               type_=mysql.VARCHAR(length=11),
               existing_nullable=False)

    with op.batch_alter_table('tbl_dorm_rooms', schema=None) as batch_op:
        batch_op.drop_constraint('fk_dorm_room_student', type_='foreignkey')

    # ### end Alembic commands ###
