"""change Student_age to integer

Revision ID: e6efcf72b892
Revises: 426a10f0823e
Create Date: 2023-12-05 17:45:22.085452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6efcf72b892'
down_revision = '426a10f0823e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_student', schema=None) as batch_op:
        batch_op.alter_column('student_age',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_student', schema=None) as batch_op:
        batch_op.alter_column('student_age',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)

    # ### end Alembic commands ###
